version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    env_file:
      - .env 
    environment:
      DB_USER : ${DB_USER}
      DB_PASSWORD : ${DB_PASSWORD}
      DB_HOST : mysql
      DB_NAME : ${DB_NAME}
    networks:
      - my_network
    

  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}    
      MYSQL_DATABASE: ${DB_NAME}
    networks:
      - my_network

networks:
  my_network:
    driver: bridge


volumes:
  mysql_data: {}